const PERMISSIONS = {
    USER_CREATE : "USER_CREATE",
    USER_PROMOTE : "USER_PROMOTE",
    USER_DELETE : "USER_DELETE",
    FILE_UPLOAD : "FILE_UPLOAD",
    FILE_VIEW : "FILE_VIEW",
    FILE_DELETE : "FILE_DELETE",
    AUDIT_VIEW : "AUDIT_VIEW",
    REPORT_GENERATE : "REPORT_GENERATE",
    ROLE_VIEW : "ROLE_VIEW"
};

module.exports = PERMISSIONS;